name: My First Workflow

on:
  workflow_dispatch:

jobs:
  first-pipeline:
    runs-on: self-hosted
    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/pierre-semay/hello-world-nginx:v1 -t ghcr.io/pierre-semay/hello-world-nginx:${{ github.ref_name }} -t ghcr.io/pierre-semay/hello-world-nginx:${{ github.sha }} .

      - name: Push to GitHub Container Registry
        run: docker push --all-tags ghcr.io/pierre-semay/hello-world-nginx

      - name: Stop any existing containers
        run: docker rm -f hello-world-nginx
        continue-on-error: true

      - name: Run Docker container
        run: docker run -d -p 8081:80 --name hello-world-nginx ghcr.io/pierre-semay/hello-world-nginx:v1

      - name: Verify container is running
        run: |
          Start-Sleep -Seconds 3
          curl.exe http://localhost:8081